"""Research Paper Writer — auto-generate LaTeX paper from experiment results.

Collects: architecture, training curves, evaluation metrics, comparisons.
Generates: full LaTeX paper with abstract, intro, method, experiments, conclusion.
"""

from __future__ import annotations

import json
import time
from typing import Any


def generate_paper(
    title: str,
    architecture: dict,
    training_config: dict,
    eval_results: dict,
    experiments: list[dict] = None,
    abstract_hint: str = "",
    key_contribution: str = "",
    ai_assistant=None,
) -> dict:
    """Generate a research paper as LaTeX."""

    # Collect all data
    nodes = architecture.get("nodes", [])
    layer_desc = " → ".join(n.get("layer_type", "?") for n in nodes)
    total_params = sum(n.get("params", {}).get("out_features", 0) for n in nodes)

    # Build paper context
    context = f"""Architecture: {layer_desc}
Training: {json.dumps(training_config, indent=2)}
Evaluation: {json.dumps(eval_results, indent=2)}
Experiments compared: {len(experiments or [])}
Key contribution: {key_contribution}"""

    # If AI is available, use it for better writing
    if ai_assistant and ai_assistant._configured:
        return _generate_with_ai(title, context, abstract_hint, key_contribution, ai_assistant,
                                  architecture, training_config, eval_results, experiments)

    # Fallback: template-based generation
    return _generate_template(title, architecture, training_config, eval_results, experiments,
                               abstract_hint, key_contribution)


def _generate_with_ai(title, context, abstract_hint, key_contribution, ai, arch, tc, eval_res, experiments):
    """Use AI to write a better paper."""
    prompt = f"""Write a complete research paper in LaTeX format.

Title: {title}
{f'Abstract hint: {abstract_hint}' if abstract_hint else ''}
{f'Key contribution: {key_contribution}' if key_contribution else ''}

Context:
{context}

Generate a complete LaTeX paper with these sections:
1. Abstract
2. Introduction (motivation, problem, contribution)
3. Related Work (cite relevant prior work based on the method described)
4. Method (describe the architecture in detail)
5. Experiments (training setup, datasets, baselines, results table)
6. Results & Analysis (interpret the metrics)
7. Ablation Study (if experiments data available)
8. Conclusion

Use proper LaTeX formatting with \\section, \\subsection, tables, and \\begin{{figure}} environments.
Include a results comparison table if multiple experiments exist.
Return ONLY the LaTeX code."""

    result = ai.chat(prompt)
    if result["status"] == "ok":
        # Extract LaTeX from response
        latex = result["response"]
        # Clean up markdown fences if present
        latex = latex.replace("```latex", "").replace("```", "")
        return {"status": "ok", "latex": latex, "method": "ai"}

    return {"status": "error", "message": result.get("message", "AI failed")}


def _generate_template(title, architecture, training_config, eval_results, experiments, abstract_hint, key_contribution):
    """Template-based paper generation (no AI needed)."""
    nodes = architecture.get("nodes", [])
    layer_desc = " $\\rightarrow$ ".join(f"\\texttt{{{n.get('layer_type', '?')}}}" for n in nodes)

    # Build results table
    results_table = ""
    if experiments:
        rows = []
        for exp in experiments:
            name = exp.get("name", "?")
            val_acc = exp.get("best_val_acc")
            val_loss = exp.get("best_val_loss")
            params = exp.get("total_params", 0)
            rows.append(f"    {name} & {params:,} & {f'{val_loss:.4f}' if val_loss else '-'} & {f'{val_acc*100:.1f}\\%' if val_acc else '-'} \\\\")
        results_table = "\n".join(rows)

    accuracy = eval_results.get("accuracy", eval_results.get("r2", None))
    f1 = eval_results.get("macro_f1") or eval_results.get("weighted_f1")

    latex = f"""\\documentclass[11pt]{{article}}
\\usepackage[utf8]{{inputenc}}
\\usepackage{{amsmath, amssymb, amsthm}}
\\usepackage{{graphicx}}
\\usepackage{{booktabs}}
\\usepackage{{hyperref}}
\\usepackage{{algorithm, algorithmic}}
\\usepackage[margin=1in]{{geometry}}

\\title{{{title}}}
\\author{{Generated by StateGraph}}
\\date{{\\today}}

\\begin{{document}}
\\maketitle

\\begin{{abstract}}
{abstract_hint or f"We propose a novel neural network architecture that achieves competitive results on the evaluated benchmarks. Our approach, consisting of {len(nodes)} layers ({layer_desc}), demonstrates {f'an accuracy of {accuracy*100:.1f}%' if accuracy and accuracy <= 1 else f'a score of {accuracy}' if accuracy else 'promising performance'} on the evaluation dataset. {key_contribution or 'The architecture is designed for simplicity and efficiency, making it suitable for rapid prototyping and research.'}"}
\\end{{abstract}}

\\section{{Introduction}}

Deep learning has achieved remarkable success across a wide range of tasks. However, designing effective architectures remains a challenging and time-consuming process. In this work, we present a {len(nodes)}-layer architecture that {key_contribution or 'achieves competitive performance with a simple and interpretable design'}.

Our main contributions are:
\\begin{{itemize}}
    \\item A novel architecture combining {layer_desc}
    \\item Comprehensive evaluation showing {'strong' if accuracy and accuracy > 0.8 else 'competitive'} performance
    \\item Analysis of training dynamics and architectural choices
\\end{{itemize}}

\\section{{Related Work}}

Neural architecture design has been extensively studied across multiple paradigms. Foundational work on residual connections \\cite{{he2016deep}} enabled training of much deeper networks, while the Transformer architecture \\cite{{vaswani2017attention}} introduced self-attention as a powerful alternative to recurrence. Subsequent work on efficient architectures includes MobileNets \\cite{{howard2017mobilenets}} for resource-constrained deployment and neural architecture search \\cite{{zoph2017neural}} for automated design. Our approach builds on these foundations by {key_contribution or 'combining established components in a novel configuration tailored to the target task'}.

\\section{{Method}}

\\subsection{{Architecture}}

Our model consists of {len(nodes)} layers arranged sequentially:

$$\\text{{Input}} {layer_desc} \\text{{Output}}$$

\\begin{{table}}[h]
\\centering
\\caption{{Architecture details}}
\\begin{{tabular}}{{llll}}
\\toprule
\\textbf{{Layer}} & \\textbf{{Type}} & \\textbf{{Parameters}} & \\textbf{{Activation}} \\\\
\\midrule
{chr(10).join(f"    {i+1} & \\texttt{{{n.get('layer_type', '?')}}} & {json.dumps(n.get('params', {}))} & {n.get('activation', '-')} \\\\\\\\" for i, n in enumerate(nodes))}
\\bottomrule
\\end{{tabular}}
\\end{{table}}

\\subsection{{Training Configuration}}

We train the model with the following configuration:
\\begin{{itemize}}
    \\item Optimizer: {training_config.get('optimizer', 'Adam')} with learning rate {training_config.get('learning_rate', 0.001)}
    \\item Batch size: {training_config.get('batch_size', 32)}
    \\item Epochs: {training_config.get('epochs', 10)}
    \\item Loss function: {training_config.get('loss', 'CrossEntropyLoss')}
    {f"\\item LR Scheduler: {training_config.get('scheduler')}" if training_config.get('scheduler') else ''}
\\end{{itemize}}

\\section{{Experiments}}

\\subsection{{Setup}}

{f"The model is trained on {training_config.get('dataset', 'the target dataset')} using {training_config.get('optimizer', 'Adam')} with a learning rate of {training_config.get('learning_rate', 0.001)}." if training_config else 'We evaluate on a standard benchmark dataset with the training configuration described below.'}

\\subsection{{Results}}

{f'''
\\begin{{table}}[h]
\\centering
\\caption{{Comparison of architectures}}
\\begin{{tabular}}{{lccc}}
\\toprule
\\textbf{{Model}} & \\textbf{{Params}} & \\textbf{{Val Loss}} & \\textbf{{Val Acc}} \\\\
\\midrule
{results_table}
\\bottomrule
\\end{{tabular}}
\\end{{table}}
''' if results_table else ''}

Our model achieves{f' an accuracy of {accuracy*100:.1f}\\%' if accuracy and accuracy <= 1 else ''}{f' with an F1 score of {f1*100:.1f}\\%' if f1 else ''}.

% \\begin{{figure}}[h]
% \\centering
% \\includegraphics[width=0.8\\textwidth]{{training_curve.png}}
% \\caption{{Training loss curve}}
% \\end{{figure}}

\\section{{Analysis}}

{f"Our model achieves {f'an accuracy of {accuracy*100:.1f}%' if accuracy and accuracy <= 1 else f'a score of {accuracy}' if accuracy else 'competitive performance'}{f' and an F1 score of {f1*100:.1f}%' if f1 else ''}. " if accuracy or f1 else ''}The architecture consists of {len(nodes)} layers with a total parameter count suitable for the target application. We observe that the choice of {training_config.get('optimizer', 'optimizer')} with {'a cosine annealing schedule' if training_config.get('scheduler') else 'a fixed learning rate'} provides stable convergence throughout training.

\\section{{Conclusion}}

We presented a {len(nodes)}-layer neural network architecture that {'demonstrates strong performance' if accuracy and accuracy > 0.8 else 'achieves competitive results'} on the evaluated benchmarks. {key_contribution or 'The simplicity of the architecture makes it a good starting point for further research and extension.'}

Future work includes:
\\begin{{itemize}}
    \\item Scaling to larger datasets and model sizes
    \\item Investigating architectural variations
    \\item Comparing with state-of-the-art methods
\\end{{itemize}}

\\bibliographystyle{{plain}}
% \\bibliography{{references}}

\\end{{document}}
"""

    return {"status": "ok", "latex": latex, "method": "template"}
